### PR TITLE
add frcnn specific layers

### PR DESCRIPTION
**Pull request by liuziwei7**

### CODE REVIEW

**Comment by yjxiong** [comment]
Thanks. Will test and merge to master.

**Comment by yjxiong** [comment]
Closing this as I am making a new PR to incorporate fast/faster RCNN features.

**Comment by SophieZhou** [comment]
If you use python layer, you can not do multi gpu job.

**Comment by yjxiong** [comment]
Hi @SophieZhou,
In our implementation, it's perfectly ok to use Python layer in multiGPU training. Only thing to take care of is to let the python layer know its rank. 

This can be done by using the  python MPI wrapper. I will add an example illustrating this pattern.

**Comment by SophieZhou** [comment]
Expecting your example. But I am puzzled. As I understand, you just only want to replace your caffe with the caffe in fast rcnn. As I have not found any lib functions here which are used in fast rcnn.

**Comment by yjxiong** [comment]
The response is just to answer your question on Python layer. Actually Python layers can be handful for data feeding in many tasks. So showing how to use Python layers in Multi-GPU training may also benefit other users.

**Comment by SophieZhou** [comment]
@yjxiong Thanks very much. I've got it.  Expecting.

**Pull request closed without merging**
